apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5050
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5050
            initialDelaySeconds: 2
            periodSeconds: 5
