apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-vault
    kind: SecretStore
  target:
    name: demo-service-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: demo-api-key
