apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:v2
          imagePullPolicy: Never
          env:
            - name: FAILURE_RATE
              value: "0"
          ports:
            - containerPort: 5050
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5050
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5050
            initialDelaySeconds: 2
            periodSeconds: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 20s }
        - analysis:
            templates:
              - templateName: success-rate
            args:
              - name: service-name
                value: demo-service
        - setWeight: 50
        - pause: { duration: 20s }
        - analysis:
            templates:
              - templateName: success-rate
            args:
              - name: service-name
                value: demo-service
        - setWeight: 100
