apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-vault
spec:
  provider:
    fake:
      data:
        - key: demo-api-key
          value: "super-secret-value-from-vault-12345"
